name: node.js package

-on: 
  -push:
    - main
      
  jobs:
    publish-gpr:
      runs-on: ubuntu-latest
        
      steps:
        - name: checkout          
          uses: actions/checkout@v2
          
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 20              
            registry-url: https://npm.pkg.github.com/
            scope: '@Phoenix-Modules'
        - run: yarn
        - run: yarn build
        - run: yarn publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}